Django_practice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("Todo_List.urls", namespace="todo_list")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Todo_List/urls.py
from django.urls import path

from Todo_List.views import (TagsListView,
                             TagsCreateView,
                             TagsUpdateView,
                             TagsDeleteView,
                             TaskListView,
                             TaskCreateView,
                             done_task,
                             TaskUpdateView,
                             TaskDeleteView)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("tags/", TagsListView.as_view(), name="tags-list"),
    path("tags/create/", TagsCreateView.as_view(), name="tags-create"),
    path("tags/<int:pk>/update/", TagsUpdateView.as_view(), name="tags-update"),
    path("tags/<int:pk>/delete/", TagsDeleteView.as_view(), name="tags-delete"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/done-task/", done_task, name="done-task")
]

app_name = "todo_list"

django_practice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_list/urls.py
from django.urls import path

from todo_list.views import (TagsListView,
                             TagsCreateView,
                             TagsUpdateView,
                             TagsDeleteView,
                             TaskListView,
                             TaskCreateView,
                             DoneTask,
                             TaskUpdateView,
                             TaskDeleteView)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("tags/", TagsListView.as_view(), name="tags-list"),
    path("tags/create/", TagsCreateView.as_view(), name="tags-create"),
    path("tags/<int:pk>/update/", TagsUpdateView.as_view(), name="tags-update"),
    path("tags/<int:pk>/delete/", TagsDeleteView.as_view(), name="tags-delete"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/done-task/", DoneTask.post, name="done-task")
]

app_name = "todo_list"

todo_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField()
    deadline = models.DateTimeField(blank=False)
    ready = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")

Todo_List/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from django.shortcuts import render

from Todo_List.models import Tag, Task


class TagsListView(generic.ListView):
    model = Tag
    context_object_name = "tags_list"
    template_name = "todo_list/tags-list.html"


class TagsCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    context_object_name = "tags_form"
    template_name = "todo_list/tags_form.html"
    success_url = reverse_lazy("todo_list:tags-list")


class TagsUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    context_object_name = "tags_form"
    template_name = "todo_list/tags_form.html"
    success_url = reverse_lazy("todo_list:tags-list")


class TagsDeleteView(generic.DeleteView):
    model = Tag
    context_object_name = "tags_delete"
    template_name = "todo_list/tags_delete.html"
    success_url = reverse_lazy("todo_list:tags-list")


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "todo_list/task_list.html"


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    context_object_name = "task_form"
    template_name = "todo_list/task_form.html"
    success_url = reverse_lazy("todo_list:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    context_object_name = "task_form"
    template_name = "todo_list/task_form.html"
    success_url = reverse_lazy("todo_list:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    context_object_name = "task_delete"
    template_name = "todo_list/task_delete.html"
    success_url = reverse_lazy("todo_list:index")


def done_task(request, pk):
    if Task.objects.get(id=pk).ready:
        Task.objects.filter(id=pk).update(ready=False)
    else:
        Task.objects.filter(id=pk).update(ready=True)
    return HttpResponseRedirect(reverse_lazy("todo_list:index"))

todo_list/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from django.shortcuts import render, get_object_or_404

from todo_list.models import Tag, Task


class TagsListView(generic.ListView):
    model = Tag
    context_object_name = "tags_list"
    template_name = "todo_list/tags-list.html"


class TagsCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    context_object_name = "tags_form"
    template_name = "todo_list/tags_form.html"
    success_url = reverse_lazy("todo_list:tags-list")


class TagsUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    context_object_name = "tags_form"
    template_name = "todo_list/tags_form.html"
    success_url = reverse_lazy("todo_list:tags-list")


class TagsDeleteView(generic.DeleteView):
    model = Tag
    context_object_name = "tags_delete"
    template_name = "todo_list/tags_delete.html"
    success_url = reverse_lazy("todo_list:tags-list")


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "todo_list/task_list.html"


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    context_object_name = "task_form"
    template_name = "todo_list/task_form.html"
    success_url = reverse_lazy("todo_list:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    context_object_name = "task_form"
    template_name = "todo_list/task_form.html"
    success_url = reverse_lazy("todo_list:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    context_object_name = "task_delete"
    template_name = "todo_list/task_delete.html"
    success_url = reverse_lazy("todo_list:index")


class DoneTask:
    def post(request, pk):
        task = get_object_or_404(Task, pk=pk).ready
        if task:
            Task.objects.filter(pk=pk).update(ready=False)
        else:
            Task.objects.filter(pk=pk).update(ready=True)
        return HttpResponseRedirect(reverse_lazy("todo_list:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Taxi Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}


        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo_list:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_list:tags-list' %}">Tags</a></li>
</ul>

templates/todo_list/tags-list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>Tags
        <a href="{% url 'todo_list:tags-create' %}" class="btn btn-primary link-to-page">
      Create
        </a>
    </h1>
    <table class="table">
       <tr>
         <th>Name</th>
         <th>Update</th>
         <th>Delete</th>
       </tr>
        {% for tag in tags_list %}
            <tr>
              <td>{{ tag.name }}</td>
              <td>
                  <a href="{% url 'todo_list:tags-update' pk=tag.id %}" class="btn btn-primary link-to-page">
                    Update
                  </a>
              </td>
              <td>
                  <a href="{% url 'todo_list:tags-delete' pk=tag.id %}" class="btn btn-primary link-to-page">
                    Delete
                  </a>
              </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/todo_list/tags_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_list/tags_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/task_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>TODO list
        <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary link-to-page">
          Add task
        </a>
    </h1>
    <table class="table">
        {% for task in task_list %}
            {% if task.ready %}
                <tr>
                    <th>{{ task.content }} <a style="color:Green">Done</a></th>
                    <td>
                        Created: {{ task.datetime }} Deadline: {{ task.deadline }}
                    </td>
                    <td>
                        Tags:{% for tag in task.tags.all %}
                             {{ tag.name }}{% endfor %} <a href="{% url 'todo_list:task-update' pk=task.id %}">Update</a> <a href="{% url 'todo_list:task-delete' pk=task.id %}">Delete</a>

                    </td>
                    <td>
                        <a href="{% url 'todo_list:done-task' pk=task.id %}" class="btn btn-danger">undo</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <th>{{ task.content }} <a style="color:red">Not done</a></th>
                    <td>
                        Created: {{ task.datetime }} Deadline: {{ task.deadline }}
                    </td>
                    <td>
                        Tags:{% for tag in task.tags.all %}
                             {{ tag.name }}{% endfor %} <a href="{% url 'todo_list:task-update' pk=task.id %}">Update</a> <a href="{% url 'todo_list:task-delete' pk=task.id %}">Delete</a>

                    </td>
                    <td>
                        <a href="{% url 'todo_list:done-task' pk=task.id %}" class="btn btn-success link-to-page">Done</a>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
{% endblock %}